# ==================================================
#  KoolDots (2026)
#  Project URL: https://github.com/LinuxBeginnings
#  License: GNU GPLv3
#  SPDX-License-Identifier: GPL-3.0-or-later
# ==================================================
# Commands and Apps to be executed at launch
exec-once = copyq --start-server

# Custom battery and AC power rules monitor
exec-once = $UserScripts/BatteryMonitor.sh
exec-once = $UserScripts/PowerStateMonitor.sh
