# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Hypridle - Battery Power Profile

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# Dim after 30s idle
listener {
    timeout = 30
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# Lock after 1m idle
listener {
    timeout = 60
    on-timeout = pidof hyprlock || hyprlock
}

# Sleep after 5m idle
listener {
    timeout = 300
    on-timeout = systemctl suspend
}
