# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Hypridle - AC Power Profile

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# Dim after 1m idle
listener {
    timeout = 60
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# Lock after 2m idle
listener {
    timeout = 120
    on-timeout = pidof hyprlock || hyprlock
}

# Sleep after 1h idle
listener {
    timeout = 3600
    on-timeout = systemctl suspend
}
